### ISSUE TITLE
Custom name issues

### ISSUE THREAD

**Issue by Cobwebster** [Leonidius20/TradingCommands#1]
Can you make it so it'll deny any items from being listed if it has HasCustomName. players can rename random items to "Beacon" for example and fake listings.

**Comment by JustTalDevelops** [comment]
Yeah, it causes a ton of scamming on the servers, it’d be very easier if you just made a check for names that don’t match the actual ID.

**Comment by Leonidius20** [comment]
If you mean auction, it displays item's original name even if it has a custom one

**Comment by JustTalDevelops** [comment]
Are you sure? It dosent work like that for us, it displays the renamed item

**Comment by Leonidius20** [comment]
> Are you sure? It dosent work like that for us, it displays the renamed item

Sorry for inactivity. I don't have much free time nowadays, I will fix the issue as soon as I have time. Meanwhile, can you check the newest version of Trading Interface? You've reported a bug that doesn't allow people with underscores in their names to open the shop. I changed a few things there, so it may be fixed in 1.0.3.

**Comment by JustTalDevelops** [comment]
Yeah, it works great now! We just need the item naming fixed because it allows for players to be scammed. Please tell me when you do have a fix, thanks! Also, is there a way to limit how much you can auction for? Players are typing in numbers that spam the whole chat, or maybe make a editable language file.

**Comment by JustTalDevelops** [comment]
Hey!
Has the plugin been updated yet?

**Comment by JustTalDevelops** [comment]
The bug is really delaying us.

**Comment by Leonidius20** [comment]
Sorry, I haven't fixed this yet. I don't have much time because of the preparation for exams. I hope I will fix it tonight

**Comment by Leonidius20** [comment]
> The bug is really delaying us.

Must be fixed now: https://github.com/Leonidius20/TradingCommands/releases/download/1.0.4/Trading.jar

**Comment by Leonidius20** [comment]
@TalhaAzeem37 is it fixed now? Can I close this issue?
